# Generated by Django 2.2.2 on 2020-03-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='u_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
