# Generated by Django 2.2.2 on 2020-03-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_u_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='u_date',
        ),
    ]
